// Palet monokrom print-first (spec §4) — tanpa aksen berwarna, tanpa gradient.
export const MONO = {
  ink: [17, 17, 17],
  sub: [90, 90, 90],
  faint: [150, 150, 150],
  rule: [190, 190, 190],
  headFill: [232, 232, 232],
  zebra: [248, 248, 248],
  white: [255, 255, 255],
};

// Ritme vertikal per profil (mm). Nilai A4 dipertahankan persis sama dengan
// engine Task 7; A5 memakai tune-up compact dari preseden generateNotaPDF.js:312-323.
const A4_METRICS = {
  lineH: 4,
  tableGap: 5,
  sigGap: 5,
  sigLineOffset: 19,
  sigNameOffset: 24,
  footerGap: 4,
  detailStep: 4.2,
  sectionGap: 4,
  nameStep: 4.6,
  infoStep: 4.4,
  companyStep: 5,
  headingStep: 4.2,
  summaryStep: 5,
  procurementLead: 5.5,
  dividerMin: 24,
  tableStartOffset: 33,
  barcodeWidth: 38,
  barcodeHeight: 7,
};

const A5_METRICS = {
  lineH: 2.6,
  tableGap: 3.5,
  sigGap: 4,
  sigLineOffset: 12,
  sigNameOffset: 17,
  footerGap: 2.5,
  detailStep: 3.3,
  sectionGap: 3,
  nameStep: 3.8,
  infoStep: 3.6,
  companyStep: 4.2,
  headingStep: 3.3,
  summaryStep: 4,
  procurementLead: 4.6,
  dividerMin: 24,
  tableStartOffset: 31,
  barcodeWidth: 32,
  barcodeHeight: 6,
};

// Ritme A6 (nota operasional, spec §8). Basis tune-up legacy generateNotaPDF.js
// (isA6: lineH 2.1, sigLineOffset 8, sigNameOffset 12, tableGap 2.5) dengan
// penyesuaian header satu baris + barcode 34×5 mm. CODE128 "HSB-NOTA-2609001"
// = 189 modul → X-dimension 0,18 mm (7,1 mil); legacy A6 26 mm hanya 0,14 mm
// (5,4 mil), jadi 34 mm adalah ukuran minimum yang lebih aman dipindai.
const A6_METRICS = {
  lineH: 2.1,
  tableGap: 2.5,
  sigGap: 3,
  sigLineOffset: 8,
  sigNameOffset: 12,
  footerGap: 1.5,
  detailStep: 3.2,
  sectionGap: 2.5,
  nameStep: 3.6,
  infoStep: 3.4,
  companyStep: 4,
  headingStep: 3.2,
  summaryStep: 4,
  procurementLead: 4,
  dividerMin: 13,
  tableStartOffset: 24,
  barcodeWidth: 34,
  barcodeHeight: 5,
  continuationLineY: 15,
};

// Profil per ukuran kertas. Bentuk kontrak sama untuk semua ukuran; kunci
// komposisi (customerRefs2Col, compactHeader, splitTail) mengikuti spec §7,
// kunci A6 (oneLineHeader, shortCustomer, qtyWithUnit, compactSummary,
// externalRefMode) mengikuti spec §8.
export const DOCUMENT_PROFILES = {
  A4: {
    title: 'FAKTUR PENJUALAN',
    subtitle: 'SALES INVOICE',
    paper: 'a4',
    orientation: 'p',
    margin: 12,
    baseFontSize: 10,
    titleFontSize: 14,
    tableFontSize: 8.5,
    tableCellPadding: 1.8,
    showParties2Col: true,
    customerRefs2Col: false,
    compactHeader: false,
    splitTail: false,
    maxProcurementRefs: Infinity,
    batchMetaMode: 'always',
    showTaxRef: true,
    signatureCount: 3,
    recommendedItems: 12,
    metrics: A4_METRICS,
  },
  A5: {
    title: 'NOTA PENJUALAN',
    subtitle: null,
    paper: 'a5',
    orientation: 'l',
    margin: 8,
    baseFontSize: 8,
    titleFontSize: 12,
    tableFontSize: 6.5,
    tableCellPadding: 0.6,
    showParties2Col: false,
    customerRefs2Col: true,
    compactHeader: true,
    splitTail: true,
    maxProcurementRefs: 2,
    batchMetaMode: 'compact',
    showTaxRef: false,
    signatureCount: 2,
    recommendedItems: 7,
    metrics: A5_METRICS,
  },
  A6: {
    title: 'NOTA PENJUALAN',
    subtitle: null,
    paper: 'a6',
    orientation: 'l',
    margin: 5,
    baseFontSize: 7,
    titleFontSize: 9,
    tableFontSize: 6,
    tableCellPadding: 0.5,
    showParties2Col: false,
    customerRefs2Col: false,
    compactHeader: true,
    oneLineHeader: true,
    shortCustomer: true,
    qtyWithUnit: true,
    tableColumns: 'compact',
    splitTail: true,
    compactSummary: true,
    grandTotalBoost: 2,
    notesMaxLines: 2,
    continuationCustomer: true,
    maxProcurementRefs: 1,
    externalRefMode: 'short',
    batchMetaMode: 'fit',
    showTaxRef: false,
    signatureCount: 2,
    recommendedItems: 5,
    metrics: A6_METRICS,
  },
};
